### ISSUE TITLE
Implement offer modification

### ISSUE THREAD

**Issue by gzili** [gzili/foodsaver#31]
Allow of modification of offer **by the creator** by sending a `PUT` request to `/api/offers/{id}` (where id is an integer, representing the offer ID. The endpoint receives data in this format:

```c#
class UpdateOfferDto {
  string FoodName;
  string FoodUnit;
  double Quantity;
  DateTime ExpirationDate;
  string Description;
}
```

**Comment by ago-ble** [comment]
https://github.com/gzili/foodsaver/pull/49
